### ISSUE TITLE
start command

### ISSUE THREAD

**Issue by intersector** [mvaal/rain-dance#4]
Hello,
 I build your project but I have an issue with the rd!start.
When i type it, it returns wrong command.
Which is the format of the command
Thank you very much in advance!

**Comment by mvaal** [comment]
Hey, thanks for your interest in my project! I haven't had a chance to work on this in a while, but will take a look at what is wrong with the commands when I get home, thanks for letting me know.  Will get back to you.

**Comment by mvaal** [comment]
hey @intersector, you need to use rd!start latitude,longitude.
I have updated the README and the bot commands.  Thanks for your feedback.

**Comment by intersector** [comment]
Oh thank you very much, I feel a bit stupid.
I was trying **rd!start lat, long**  **rd!start lat long** i always had " " between lat and long  :( 
Sorry and thanks for your help!!!

**Comment by mvaal** [comment]
No problem.  I will see what I can do to make it more clear in the future.  Thanks again!
